/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crud;

import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Menu extends javax.swing.JFrame {

    Login bb = new Login();
    
    public Menu() {
        if (Session.getStatusLogin() == "AKTIF"){    
        initComponents();
        setSessionNama();
    }else{
    dispose();
    
    FormLogin form = new FormLogin();
    form.setVisible(true);
    }
}
    private void setSessionNama(){
        label_nama.setText("Hai "+Session.getNama());
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_nama = new javax.swing.JLabel();
        label_keterangan = new javax.swing.JLabel();
        jMenuAplikasiBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuKeluar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuCRUDSiswa = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_nama.setText("Hai");

        label_keterangan.setText("Selamat datang di Aplikasi Praktikum CRUD");

        jMenu1.setText("Aplikasi");

        jMenuKeluar.setText("Keluar");
        jMenuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuKeluarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuKeluar);

        jMenuAplikasiBar.add(jMenu1);

        jMenu2.setText("CRUD");

        jMenuCRUDSiswa.setText("FORM SISWA");
        jMenuCRUDSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCRUDSiswaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuCRUDSiswa);

        jMenuAplikasiBar.add(jMenu2);

        setJMenuBar(jMenuAplikasiBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_nama)
                    .addComponent(label_keterangan))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_nama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_keterangan)
                .addContainerGap(227, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCRUDSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCRUDSiswaActionPerformed
        try{
            Form_Siswa form = new Form_Siswa();
            form.setVisible(true);
            }catch(Exception ex){
        }
    }//GEN-LAST:event_jMenuCRUDSiswaActionPerformed

    private void jMenuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuKeluarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan keluar ?","Warning",2)== JOptionPane.YES_OPTION){
        bb.Logout(Session.getUserID());
        System.exit(0);
        }
    }//GEN-LAST:event_jMenuKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuAplikasiBar;
    private javax.swing.JMenuItem jMenuCRUDSiswa;
    private javax.swing.JMenuItem jMenuKeluar;
    private javax.swing.JLabel label_keterangan;
    private javax.swing.JLabel label_nama;
    // End of variables declaration//GEN-END:variables
}
